---
title: "Homework 5 - R"
author: "Christopher Halim"
date: "3/26/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Number 1
```{r}
mat1.data <- c(1.0000,0.6328,0.2412,0.0586,0.6328,1.0000,-0.0553,0.0665,0.2412,-0.0553,1.0000,0.4248,0.0586,0.0655,0.4248,1.0000)
mat1 <- matrix(mat1.data,nrow = 4, ncol = 4, byrow = TRUE)
mat1

## a 
# Sample Canonical Correlation Coefficients
S <- mat1; round(S,2)
q <- 2; p <- 2
S.xx <- S[1:q, 1:q]
S.xy <- S[1:q, (q+1):(q+p)]
S.yx <- S[(q+1):(q+p), 1:q]
S.yy <- S[(q+1):(q+p),(q+1):(q+p)]

sp <- eigen(S.xx)
S.xx; sp$vectors %*% diag(sp$values) %*% t(sp$vectors)

Sxx.invsqrt <- sp$vectors %*% diag(1/sqrt(sp$values)) %*% t(sp$vectors)
sp <- eigen(S.yy)
S.yy ; sp$vectors %*% diag(sp$values) %*% t(sp$vectors)

Syy.invsqrt <- sp$vectors %*% diag(1/sqrt(sp$values)) %*% t(sp$vectors)
K.hat <- Sxx.invsqrt %*% S.xy %*% Syy.invsqrt
svd(K.hat)

foo <- svd(K.hat)
G <- foo$u; L <- diag(foo$d); D <- foo$v; rm(foo)

A.hat <- t(G) %*% Sxx.invsqrt
B.hat <- t(D) %*% Syy.invsqrt

# Sample Canonical Variables
X <- as.matrix(mat1[,1:q])
Y <- as.matrix(mat1[,(q+1):(q+p)])
n <- dim(X)[1]

eta.hat <- X %*% t(A.hat)
phi.hat <- Y %*% t(B.hat)
diag(L)

plot(eta.hat[,1], phi.hat[,1], main="First canonical variates")
plot(eta.hat[,2], phi.hat[,2], main="Second canonical variates")
A.hat[1,]
B.hat[1,]
A.hat[1,] / sqrt(sum(A.hat[1,]^2))
B.hat[1,] / sqrt(sum(B.hat[1,]^2))
A.hat[2,]
B.hat[2,]
A.hat[2,] / sqrt(sum(A.hat[2,]^2))
B.hat[2,] / sqrt(sum(B.hat[2,]^2))

## b
n <- 140
k <- min(p,q); k;
r <- svd(K.hat)$d
r
T1 <- prod(1-r^2); T1;
-(n-(p+q+3)/2) * log(T1)
1-pchisq(23.81478, df = p*q)

## c
n <- 140
T2 <- prod(1-r[-1]^2); T2;
-(n - (p+q+3)/2) * log(T2)
1 - pchisq(0.6635571, df=(p-1)*(q-1))

## d

 

```

Number 2
```{r}
mat2.data <- c(1.00,0.37,0.21,0.26,0.33,0.37,1.00,0.35,0.67,0.59,0.21,0.35,1.00,0.34,0.34,0.26,0.67,0.34,1.00,0.80,0.33,0.59,0.34,0.80,1.00)
mat2 <- matrix(mat2.data,nrow = 5, ncol = 5, byrow = TRUE)
mat2

## a 

# Sample Canonical Correlation Coefficients
S <- mat2; round(S,2)
q <- 3; p <- 2
S.xx <- S[1:q, 1:q]
S.xy <- S[1:q, (q+1):(q+p)]
S.yx <- S[(q+1):(q+p), 1:q]
S.yy <- S[(q+1):(q+p),(q+1):(q+p)]

sp <- eigen(S.xx)
S.xx; sp$vectors %*% diag(sp$values) %*% t(sp$vectors)

Sxx.invsqrt <- sp$vectors %*% diag(1/sqrt(sp$values)) %*% t(sp$vectors)
sp <- eigen(S.yy)
S.yy ; sp$vectors %*% diag(sp$values) %*% t(sp$vectors)

Syy.invsqrt <- sp$vectors %*% diag(1/sqrt(sp$values)) %*% t(sp$vectors)
K.hat <- Sxx.invsqrt %*% S.xy %*% Syy.invsqrt
svd(K.hat)

foo <- svd(K.hat)
G <- foo$u; L <- diag(foo$d); D <- foo$v; rm(foo)

A.hat <- t(G) %*% Sxx.invsqrt
B.hat <- t(D) %*% Syy.invsqrt

#p-value
n <- 70
r <- svd(K.hat)$d
r
T0 <- prod(1-r^2); T0;
-(n-(p+q+3)/2) * log(T0)
1-pchisq(44.65657, df = p*q)

## b
n <- 70
k <- min(p,q); k;
T1 <- prod(1-r[-1]^2); T1;
-(n-(p+q+3)/2) * log(T1)
1-pchisq(2.345833, df = (p-1)*(q-1))

## c
scaled.data <- scale(mat2)

# Sample Canonical Variables
X <- as.matrix(scaled.data[,1:q])
Y <- as.matrix(scaled.data[,(q+1):(q+p)])
n <- dim(X)[1]

eta.hat <- X %*% t(A.hat)
phi.hat <- Y %*% t(B.hat)
diag(L)

plot(eta.hat[,1], phi.hat[,1], main="First canonical variates")
plot(eta.hat[,2], phi.hat[,2], main="Second canonical variates")
A.hat[1,]
B.hat[1,]
A.hat[1,] / sqrt(sum(A.hat[1,]^2))
B.hat[1,] / sqrt(sum(B.hat[1,]^2))
A.hat[2,]
B.hat[2,]
A.hat[2,] / sqrt(sum(A.hat[2,]^2))
B.hat[2,] / sqrt(sum(B.hat[2,]^2))

## d




## e




```




