---
title: "HW8"
author: "Christopher Halim"
date: "4/29/2022"
output: word_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Problem 1
```{r}
library(tidyverse)
rm(list=ls())
df <- read.csv("/Users/christopherhalim888/Downloads/Salespeople.csv")
df
dim(df); names(df)

## a
#i
cov(df)

R <- cor(df); R;

sp <- eigen(R)
sp

Gamma <- sp$vectors; Lambda <- diag(sp$values);

Gamma %*% Lambda %*% t(Gamma)

Q.hat <- (Gamma %*% sqrt(Lambda) )[,1:3]; Q.hat;
Q.hat %*% t(Q.hat)

diag(Q.hat %*% t(Q.hat)) # communaliaties

Psi.hat <- diag(diag(R - Q.hat %*% t(Q.hat)))

R - (Q.hat %*% t(Q.hat) + Psi.hat) # residual matrix

diag(Lambda)[1:3] # variances

diag(Psi.hat) # uniquenesses

#ii
varimax(Q.hat)
Q.hat %*% t(Q.hat)
Q.star <- varimax(Q.hat)$loadings
Q.star
Q.star %*% t(Q.star)

## b
#i & #ii
efa <- factanal(covmat=R, factors=3, rotation = "varimax")
efa

Psi.hat <- diag(efa$uniquenesses)
round(Psi.hat, 6)

Q2 <- matrix(as.vector(efa$loadings),7,3)
Q2

x0 <- c(15,18,12,35,110,98,105)

xbar <- apply(df, 2, mean)
round(xbar,5)

s <- apply(df, 2, sd)
round(s,6)

z0 <- (x0 - xbar) / s
round(z0, 6)

f0.hat <- t(Q.hat) %*% solve(R, z0)
f0.hat[1,]

## c
plot(f0.hat)
text(f0.hat[1,], f0.hat[2,], f0.hat[3,], df$ID, cex=.75)
```

Problem 2
```{r}
df1 <- read.csv("/Users/christopherhalim888/Downloads/irises_full.csv")
dim(df1)
names(df1)

## a
plot(jitter(x2)~jitter(x1), data = df1, pch = Species, col = Species)
legend("bottomright", inset=.05, pch=1:2, col=1:2, legend = c("Iris setosa", "Iris vericolor", "Iris virginica"))

## b
df1$Species

df1$Species <- factor(df1$Species) # Change into factor

x.new <- c(3.50,1.75) # New observation

prior <- c(1/3,1/3,1/3) # Prior probability

# Summary statistics xj and Sj
n1 <- sum(df1$Species==1) 
n2 <- sum(df1$Species==2)
n3 <- sum(df1$Species==3)
c(n1, n2, n3)

xbar1 <- colMeans(df1[df1$Species==1, 1:2])
xbar2 <- colMeans(df1[df1$Species==2, 1:2])
xbar3 <- colMeans(df1[df1$Species==3, 1:2])
xbar1; xbar2; xbar3

S1 <- cov(df1[df1$Species==1, 1:2])
S2 <- cov(df1[df1$Species==2, 1:2])
S3 <- cov(df1[df1$Species==3, 1:2])
S <- 1/(n1+n2+n3-3) * ((n1-1)*S1 + (n2-1)*S2 + (n3-1)*S3)
S

xbar <- rbind(xbar1, xbar2, xbar3)
xbar

J <- 3
L <- rep(NA,J)

for(j in 1:J){
L[j] <- log(prior[j]) + sum( (x.new-xbar[j,]/2) * solve(S,xbar[j,])) 
}

L

# Posterior Probability
exp(L - max(L)) / sum(exp(L - max(L)))

## c
library(MASS)
lda.crude <- lda(Species ~ x1+x2, data=df1)
xtabs( ~ df1$Species + predict(lda.crude)$class)
predict(lda.crude)$class

prior <- lda.crude$prior
prior

Holdout.lda <- df1$Species
 for(ij in 1:length(Holdout.lda)){
hold <- lda(Species ~ x1+x2, data=df1[-ij,], prior=prior)
Holdout.lda[ij] <- predict(hold, newdata=df1[ij,])$class 
 }
Holdout.lda

xtabs( ~ df1$Species + Holdout.lda)

Confusion <- xtabs( ~ df1$Species + Holdout.lda)
error.cv <- 1 - sum(diag(Confusion)) / sum(Confusion)
error.cv # Cross-validation error rate
```

Problem 3
```{r}
df2 <- read.csv("/Users/christopherhalim888/Downloads/Bankruptcy.csv")
dim(df2)
names(df2)

## a
library(car)
scatterplotMatrix(~ x1+x2+x3+x4, data = df2)

## b
df2$Population

df2$Population <- factor(df2$Population) # Change into factor

x.new <- c(-0.05,-0.05,1.25,0.30) # New observation
x <- x.new
x.new <- data.frame(x1=x[1], x2=x[2], x3=x[3], x4=x[4])

prior <- c(0.05,0.95) # Prior probability

library(MASS)
lda.skulls <- lda(Population ~ x1+x2+x3+x4, prior=prior, data=df2)

predict(lda.skulls, prior=prior, newdata=x.new)$class
predict(lda.skulls, prior=prior, newdata=x.new)$posterior

## c
lda.crude <- lda(Population ~ x1+x2+x3+x4, data=df2)
xtabs( ~ df2$Population + predict(lda.crude)$class)
predict(lda.crude)$class

Confusion <- xtabs( ~ df2$Population + predict(lda.crude)$class)
error.lda <- 1 - sum(diag(Confusion)) / sum(Confusion)
error.lda # Apparent error rate

prior <- lda.crude$prior
prior

Holdout.lda <- df2$Population
 for(ij in 1:length(Holdout.lda)){
hold <- lda(Population ~ x1+x2+x3+x4, data=df2[-ij,], prior=prior)
Holdout.lda[ij] <- predict(hold, newdata=df2[ij,])$class 
 }
Holdout.lda

xtabs( ~ df2$Population + Holdout.lda)

Confusion <- xtabs( ~ df2$Population + Holdout.lda)
error.cv <- 1 - sum(diag(Confusion)) / sum(Confusion)
error.cv # Cross-validation error rate
```

Problem 4
```{r}
df3 <- read.csv("/Users/christopherhalim888/Downloads/Protein.csv")
df3
dim(df3)
names(df3)

X <- as.matrix(df3[,2:10])
rownames(X) <- df3$Country

## a
R <- cor(X)
R

sp <- eigen(R)
sp

G.R <- eigen(R)$vectors; L.R <- diag(eigen(R)$values);
round(diag(L.R) / sum(diag(L.R)), 4)
round(cumsum(diag(L.R)) / sum(diag(L.R)), 4)

colnames(G.R) <- paste("NPC", 1:9, sep="")
rownames(G.R) <- colnames(X)
G.R[,1:2]

## b
D <- dist(X, method="euclidean")
round(D)

hc.complete <- hclust(D, method="complete")
plot(hc.complete, hang=-1)
rect.hclust(hc.complete, k=6, border="blue")

## c
xbar <- apply(X, 2, mean)
X.C <- sweep(X, 2, xbar, "-")
s <- apply(X, 2, sd)
X.S <- sweep(X.C, 2, s, "/")
Z <- X.S %*% G.R
rownames(Z)[order(Z[,1])]

plot(Z[,1:2], type="n")
text(Z[,1:2], rownames(Z), cex=.75)
```
